

export const POPULATE_EVENTS = "POPULATE_EVENTS";
export const ADJUST_SELECT_SEATS = "ADJUST_SELECT_SEATS";
export const ADJUST_OCC_SEATS = "ADJUST_OCC_SEATS";
export const LOAD_CURRENT_EVENT = "LOAD_CURRENT_EVENT"